/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseObjectAllOf struct {
	GatewayPoolId int32 `json:"gatewayPoolId,omitempty"`
	Name string `json:"name,omitempty"`
	NetworkId int32 `json:"networkId,omitempty"`
	ReturnData bool `json:"returnData,omitempty"`
	User AuthObject `json:"user,omitempty"`
}
