/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorError struct {
	// A JSON-RPC error code (see http://www.jsonrpc.org/specification#error_object for details)
	Code int32 `json:"code"`
	Message string `json:"message"`
}
