/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FirewallDataServicesLocalUi struct {
	Enabled bool `json:"enabled"`
	// List of IP addresses allowed UI access
	AllowSelectedIp []string `json:"allowSelectedIp,omitempty"`
	PortNumber int32 `json:"portNumber"`
	RuleLogicalId string `json:"ruleLogicalId,omitempty"`
}
