/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterDataSubnets struct {
	Advertise bool `json:"advertise,omitempty"`
	CidrIp string `json:"cidrIp,omitempty"`
	CidrIpStart string `json:"cidrIpStart,omitempty"`
	CidrIpEnd string `json:"cidrIpEnd,omitempty"`
	CidrPrefix string `json:"cidrPrefix,omitempty"`
	Name string `json:"name,omitempty"`
	NetMask string `json:"netMask,omitempty"`
}
