/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayHandoffValueBgp struct {
	Enabled bool `json:"enabled,omitempty"`
	ASN string `json:"ASN,omitempty"`
	NeighborIp string `json:"neighborIp,omitempty"`
	NeighborASN string `json:"neighborASN,omitempty"`
	Encryption bool `json:"encryption,omitempty"`
}
