/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosBusinessRulesAction struct {
	RouteType string `json:"routeType,omitempty"`
	Edge2EdgeRouteAction RouteActionObject `json:"edge2EdgeRouteAction,omitempty"`
	Edge2DataCenterRouteAction RouteActionObject `json:"edge2DataCenterRouteAction,omitempty"`
	Edge2CloudRouteAction RouteActionObject `json:"edge2CloudRouteAction,omitempty"`
	QoS map[string]interface{} `json:"QoS,omitempty"`
	Sla map[string]interface{} `json:"sla,omitempty"`
}
