/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsLanNetworkOspf struct {
	Enabled          bool  `json:"enabled,omitempty"`
	Override         bool  `json:"override,omitempty"`
	Area             int32 `json:"area"`
	PassiveInterface bool  `json:"passiveInterface,omitempty"`
}
