/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NetworkSegmentAllOf struct {
	Data NetworkSegmentData `json:"data,omitempty"`
	ProfileCount int32 `json:"profileCount,omitempty"`
	HandoffUsage []map[string]interface{} `json:"handoffUsage,omitempty"`
	IsAllMPGCDE bool `json:"isAllMPGCDE,omitempty"`
	IsAllCtrlCDE bool `json:"isAllCtrlCDE,omitempty"`
}
