/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsOspf struct {
	Enabled               bool                                `json:"enabled"`
	Areas                 []DeviceSettingsOspfArea            `json:"areas"`
	Bgp                   DeviceSettingsOspfBgpRedistribution `json:"bgp"`
	DefaultPrefixes       bool                                `json:"defaultPrefixes"`
	DefaultRouteAdvertise string                              `json:"defaultRouteAdvertise"`
	DefaultRoutes         string                              `json:"defaultRoutes"`
}
