/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterVpnTunnelIkesa struct {
	DHGroup int32 `json:"DHGroup,omitempty"`
	AuthenticationAlgorithm string `json:"authenticationAlgorithm,omitempty"`
	AuthenticationMethod string `json:"authenticationMethod,omitempty"`
	IkeVersion int32 `json:"ikeVersion,omitempty"`
	LifeTimeSeconds int32 `json:"lifeTimeSeconds,omitempty"`
	PhaseOneNegotiationMode string `json:"phaseOneNegotiationMode,omitempty"`
	SharedKey string `json:"sharedKey,omitempty"`
	SharedKeyType string `json:"sharedKeyType,omitempty"`
}
