/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeVnfSecurityVnfVm struct {
	CidrIp string `json:"cidrIp,omitempty"`
	EdgeEvent EdgeVnfSecurityVnfVmEdgeEvent `json:"edgeEvent,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	InsertionEnabled bool `json:"insertionEnabled,omitempty"`
	Ref string `json:"ref,omitempty"`
	Type string `json:"type,omitempty"`
	Vendor string `json:"vendor,omitempty"`
	VendorSpecificData map[string]interface{} `json:"vendorSpecificData,omitempty"`
	VlanId int32 `json:"vlanId,omitempty"`
	VmDeploy bool `json:"vmDeploy,omitempty"`
	VmPowerOff bool `json:"vmPowerOff,omitempty"`
}
