/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type ClientDevice struct {
	Id int32 `json:"id"`
	Created time.Time `json:"created"`
	EnterpriseId int32 `json:"enterpriseId"`
	MacAddress string `json:"macAddress"`
	HostName string `json:"hostName"`
	IpAddress string `json:"ipAddress"`
	Os int32 `json:"os"`
	OsName string `json:"osName"`
	OsVersion string `json:"osVersion"`
	DeviceType string `json:"deviceType"`
	DeviceModel string `json:"deviceModel"`
	LastContact time.Time `json:"lastContact"`
	Modified time.Time `json:"modified"`
}
