/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseGetEnterpriseServices struct {
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	Type string `json:"type,omitempty"`
	With []string `json:"with,omitempty"`
	Name string `json:"name,omitempty"`
	IncludePartnerGateways bool `json:"includePartnerGateways,omitempty"`
}
