/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsDataSnmp struct {
	Port    int32                         `json:"port,omitempty"`
	Snmpv2c DeviceSettingsDataSnmpSnmpv2c `json:"snmpv2c,omitempty"`
	Snmpv3  DeviceSettingsDataSnmpSnmpv3  `json:"snmpv3,omitempty"`
}
