/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ControlPlaneDataGatewaySelection struct {
	Mode string `json:"mode,omitempty"`
	Primary string `json:"primary,omitempty"`
	PrimaryDetail ControlPlaneDataGatewaySelectionPrimaryDetail `json:"primaryDetail,omitempty"`
	Secondary string `json:"secondary,omitempty"`
	SecondaryDetail ControlPlaneDataGatewaySelectionPrimaryDetail `json:"secondaryDetail,omitempty"`
	Super string `json:"super,omitempty"`
	SuperDetail ControlPlaneDataGatewaySelectionSuperDetail `json:"superDetail,omitempty"`
}
