/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type Tinyint int32

// List of tinyint
/*
const (
	_0 Tinyint = "0"
	_1 Tinyint = "1"
)
*/