/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosBusinessRulesMatch struct {
	Appid int32 `json:"appid,omitempty"`
	Classid int32 `json:"classid,omitempty"`
	// Integer ID indicating DSCP classification, where mappings are as follows: [EF:46,VA:44,AF11:10,AF12:12,AF13:14,AF21:18,AF22:20,AF23:22,AF31:26,AF32:28,AF33:30,AF41:34,AF42:36,AF43:38,CS0:0,CS1:8,CS2:16,CS3:24,CS4:32,CS5:40,CS6:48,CS7:56]
	Dscp int32 `json:"dscp,omitempty"`
	Sip string `json:"sip,omitempty"`
	SportHigh int32 `json:"sport_high,omitempty"`
	SportLow int32 `json:"sport_low,omitempty"`
	Ssm string `json:"ssm,omitempty"`
	Svlan int32 `json:"svlan,omitempty"`
	// Index corresponding to the OS in the array: [OTHER,WINDOWS,LINUX,MACOS,IOS,ANDROID,EDGE]
	OsVersion int32 `json:"os_version,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	Dip string `json:"dip,omitempty"`
	DportLow int32 `json:"dport_low,omitempty"`
	DportHigh int32 `json:"dport_high,omitempty"`
	Dsm string `json:"dsm,omitempty"`
	Dvlan int32 `json:"dvlan,omitempty"`
	Proto int32 `json:"proto,omitempty"`
	SRuleType string `json:"s_rule_type,omitempty"`
	DRuleType string `json:"d_rule_type,omitempty"`
}
