/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterDataIaasProviderSyncStatus struct {
	State string `json:"state,omitempty"`
	StateTimestamp int32 `json:"stateTimestamp,omitempty"`
	LastSyncTimestamp int32 `json:"lastSyncTimestamp,omitempty"`
	ErrorDetail DataCenterDataIaasProviderSyncStatusErrorDetail `json:"errorDetail,omitempty"`
}
