/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayEnterpriseAssocAllOf struct {
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	EnterpriseObjectId int32 `json:"enterpriseObjectId,omitempty"`
	EdgeId int32 `json:"edgeId,omitempty"`
	GatewayType string `json:"gatewayType,omitempty"`
	Pinned int32 `json:"pinned,omitempty"`
	EnterpriseObjectName string `json:"enterpriseObjectName,omitempty"`
	EnterpriseObjectType string `json:"enterpriseObjectType,omitempty"`
	EdgeName string `json:"edgeName,omitempty"`
	EdgeLogicalId string `json:"edgeLogicalId,omitempty"`
}
