/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WanDataNetworks struct {
	Mode string `json:"mode,omitempty"`
	Type string `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
	LogicalId string `json:"logicalId,omitempty"`
	Interface string `json:"interface,omitempty"`
	InternalId string `json:"internalId,omitempty"`
	IpAddress string `json:"ipAddress,omitempty"`
	Isp string `json:"isp,omitempty"`
	LastActive int32 `json:"lastActive,omitempty"`
}
