/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayPoolGatewayUtilizationDetail struct {
	Load float32 `json:"load,omitempty"`
	Overall float32 `json:"overall,omitempty"`
	Cpu float32 `json:"cpu,omitempty"`
	Memory float32 `json:"memory,omitempty"`
}
