/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type EnterpriseAlertConfiguration struct {
	Id int32 `json:"id,omitempty"`
	Created time.Time `json:"created,omitempty"`
	AlertDefinitionId int32 `json:"alertDefinitionId,omitempty"`
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Type string `json:"type,omitempty"`
	Definition EnterpriseAlertDefinition `json:"definition,omitempty"`
	FirstNotificationSeconds int32 `json:"firstNotificationSeconds,omitempty"`
	MaxNotifications int32 `json:"maxNotifications,omitempty"`
	NotificationIntervalSeconds int32 `json:"notificationIntervalSeconds,omitempty"`
	ResetIntervalSeconds int32 `json:"resetIntervalSeconds,omitempty"`
	Modified time.Time `json:"modified,omitempty"`
}
