/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterVpnTunnelIpsecdpd struct {
	IntervalSeconds int32 `json:"intervalSeconds,omitempty"`
	Retries int32 `json:"retries,omitempty"`
	Type string `json:"type,omitempty"`
}
