/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type MonitoringGetNetworkGatewayStatus struct {
	NetworkId int32 `json:"networkId"`
	GatewayIds []int32 `json:"gatewayIds,omitempty"`
	Time time.Time `json:"time,omitempty"`
	Sort GatewayMetric `json:"sort"`
	Limit int32 `json:"limit,omitempty"`
	Metrics []GatewayMetric `json:"metrics,omitempty"`
}
