/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseInsertOrUpdateEnterpriseProperty struct {
	EnterpriseId int32 `json:"enterpriseId"`
	Name string `json:"name"`
	Value string `json:"value"`
	DataType string `json:"dataType,omitempty"`
	IsPassword bool `json:"isPassword,omitempty"`
	Description string `json:"description,omitempty"`
}
