/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseSsoAuthenticationConfigurationConfiguration struct {
	AuthorizationEndpoint string `json:"authorizationEndpoint,omitempty"`
	ClientId string `json:"clientId,omitempty"`
	ClientSecret string `json:"clientSecret,omitempty"`
	Issuer string `json:"issuer,omitempty"`
	Provider string `json:"provider,omitempty"`
	RedirectEndpoint string `json:"redirectEndpoint,omitempty"`
	TokenEndpoint string `json:"tokenEndpoint,omitempty"`
	UserInfoEndpoint string `json:"userInfoEndpoint,omitempty"`
	WellKnownConfigurationUrl string `json:"wellKnownConfigurationUrl,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	RoleConfig EnterpriseSsoAuthenticationConfigurationConfigurationRoleConfig `json:"roleConfig,omitempty"`
}
