/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeDeviceSettingsDataSnmpSnmpv3Users struct {
	Name string `json:"name,omitempty"`
	Passphrase string `json:"passphrase,omitempty"`
	AuthAlg string `json:"authAlg,omitempty"`
	Privacy bool `json:"privacy,omitempty"`
	EncrAlg string `json:"encrAlg,omitempty"`
}
