/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type License struct {
	Tier string `json:"tier,omitempty"`
	Bandwidth string `json:"bandwidth,omitempty"`
	Term float32 `json:"term,omitempty"`
	CloudGatewayRegions []string `json:"cloudGatewayRegions,omitempty"`
}
