/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseSsoAuthenticationConfiguration struct {
	Enabled bool `json:"enabled,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Provider string `json:"provider,omitempty"`
	Configuration EnterpriseSsoAuthenticationConfigurationConfiguration `json:"configuration,omitempty"`
}
