/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseRouteCollection struct {
	EligableExits []EnterpriseRoute `json:"eligableExits,omitempty"`
	PreferredExits []EnterpriseRoute `json:"preferredExits,omitempty"`
	Subnet string `json:"subnet,omitempty"`
}
