/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConfigurationCloneAndConvertConfiguration struct {
	ConfigurationId int32 `json:"configurationId"`
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	GuestVLANSegmentObjectId int32 `json:"guestVLANSegmentObjectId,omitempty"`
}
