/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type GatewaySiteAllOf struct {
	Id int32 `json:"id,omitempty"`
	Created time.Time `json:"created,omitempty"`
	Modified time.Time `json:"modified,omitempty"`
	Timezone string `json:"timezone,omitempty"`
	Locale string `json:"locale,omitempty"`
	ShippingSameAsLocation int32 `json:"shippingSameAsLocation,omitempty"`
	ShippingContactName string `json:"shippingContactName,omitempty"`
	ShippingAddress string `json:"shippingAddress,omitempty"`
	ShippingAddress2 string `json:"shippingAddress2,omitempty"`
	ShippingCity string `json:"shippingCity,omitempty"`
	ShippingState string `json:"shippingState,omitempty"`
	ShippingPostalCode string `json:"shippingPostalCode,omitempty"`
	ShippingCountry string `json:"shippingCountry,omitempty"`
}
