/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VnfVmEventDetail struct {
	ConfigUuid string `json:"configUuid,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	EdgeSerialNumber string `json:"edgeSerialNumber,omitempty"`
	IsEdgeActive bool `json:"isEdgeActive,omitempty"`
	RunningConfig map[string]interface{} `json:"runningConfig,omitempty"`
	Status string `json:"status,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	Vendor string `json:"vendor,omitempty"`
	VnfEdgeLogicalId string `json:"vnfEdgeLogicalId,omitempty"`
	VnfType string `json:"vnfType,omitempty"`
}
