/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayHandoffValue struct {
	Segments []GatewayHandoffValue `json:"segments,omitempty"`
	Segment GatewayHandoffSegmentMetadata `json:"segment,omitempty"`
	BgpPrioritySetup GatewayHandoffValueBgpPrioritySetup `json:"bgpPrioritySetup,omitempty"`
	Type string `json:"type,omitempty"`
	Override bool `json:"override,omitempty"`
	CTag int32 `json:"cTag,omitempty"`
	STag int32 `json:"sTag,omitempty"`
	LocalAddress GatewayHandoffValueLocalAddress `json:"localAddress,omitempty"`
	StaticRoutes GatewayHandoffValueStaticRoutes `json:"staticRoutes,omitempty"`
	Bgp GatewayHandoffValueBgp `json:"bgp,omitempty"`
	BgpInboundMap GatewayHandoffBgpRulesMap `json:"bgpInboundMap,omitempty"`
	BgpOutboundMap GatewayHandoffBgpRulesMap `json:"bgpOutboundMap,omitempty"`
	VLAN map[string]map[string]interface{} `json:"VLAN,omitempty"`
	Overrides GatewayHandoffValueOverrides `json:"overrides,omitempty"`
}
