/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RouteActionObject struct {
	Interface string `json:"interface,omitempty"`
	LinkInternalLogicalId string `json:"linkInternalLogicalId,omitempty"`
	LinkPolicy string `json:"linkPolicy,omitempty"`
	RouteCfg map[string]interface{} `json:"routeCfg,omitempty"`
	RoutePolicy string `json:"routePolicy,omitempty"`
	ServiceGroup string `json:"serviceGroup,omitempty"`
	VlanId int32 `json:"vlanId,omitempty"`
	Wanlink string `json:"wanlink,omitempty"`
	LinkCosLogicalId string `json:"linkCosLogicalId,omitempty"`
	LinkOuterDscpTag string `json:"linkOuterDscpTag,omitempty"`
	LinkInnerDscpTag string `json:"linkInnerDscpTag,omitempty"`
}
