/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsNetflow struct {
	Enabled    bool                             `json:"enabled"`
	Override   bool                             `json:"override"`
	Collectors []DeviceSettingsNetflowCollector `json:"collectors"`
	Version    int32                            `json:"version"`
	Intervals  DeviceSettingsNetflowIntervals   `json:"intervals"`
}
