/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterVpnTunnel struct {
	IKESA DataCenterVpnTunnelIkesa `json:"IKESA,omitempty"`
	IPSECDPD DataCenterVpnTunnelIpsecdpd `json:"IPSECDPD,omitempty"`
	IPSECSA DataCenterVpnTunnelIpsecsa `json:"IPSECSA,omitempty"`
	DataCenterLinkIp string `json:"dataCenterLinkIp,omitempty"`
	DataCenterPublicIp string `json:"dataCenterPublicIp,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
	FragmentationAvoidance DataCenterVpnTunnelFragmentationAvoidance `json:"fragmentationAvoidance,omitempty"`
	GatewayLinkIp string `json:"gatewayLinkIp,omitempty"`
	GatewayPublicIp string `json:"gatewayPublicIp,omitempty"`
	GeoData DataCenterVpnTunnelGeoData `json:"geoData,omitempty"`
	//Redundant DataCenterVpnTunnel `json:"redundant,omitempty"`
	ServiceFQDN string `json:"serviceFQDN,omitempty"`
	TunnelInterface DataCenterVpnTunnelTunnelInterface `json:"tunnelInterface,omitempty"`
	Type string `json:"type,omitempty"`
	TypeAlias string `json:"typeAlias,omitempty"`
}
