/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsVpnEdgeToEdgeDetailDynamic struct {
	Enabled   bool                              `json:"enabled"`
	Isolation DeviceSettingsVpnProfileIsolation `json:"isolation,omitempty"`
	Type      string                            `json:"type,omitempty"`
	Timeout   int32                             `json:"timeout,omitempty"`
}
