/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayHandoffDetailIcmpProbe struct {
	Enabled bool `json:"enabled,omitempty"`
	ProbeType string `json:"probeType,omitempty"`
	CTag int32 `json:"cTag,omitempty"`
	STag int32 `json:"sTag,omitempty"`
	DestinationIp string `json:"destinationIp,omitempty"`
	FrequencySeconds int32 `json:"frequencySeconds,omitempty"`
	Threshold int32 `json:"threshold,omitempty"`
}
