/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Application struct {
	Class int32 `json:"class"`
	Description string `json:"description"`
	DisplayName string `json:"displayName"`
	Name string `json:"name,omitempty"`
	Id int32 `json:"id"`
	KnownIpPortMapping IpPortMapping `json:"knownIpPortMapping"`
	ProtocolPortMapping ProtocolPortMapping `json:"protocolPortMapping"`
}
