/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ControlPlaneData struct {
	GatewaySelection ControlPlaneDataGatewaySelection `json:"gatewaySelection"`
	Vpn ControlPlaneDataVpn `json:"vpn,omitempty"`
	IpsecGatewayDetail map[string]GatewayPoolGatewayIpsecGatewayDetail `json:"ipsecGatewayDetail,omitempty"`
}
