/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsCloudSecurity struct {
	Enabled  bool                                `json:"enabled"`
	Override bool                                `json:"override,omitempty"`
	Config   DeviceSettingsCloudSecurityConfig   `json:"config,omitempty"`
	Provider DeviceSettingsCloudSecurityProvider `json:"provider,omitempty"`
	Sites    []DeviceSettingsCloudSecuritySite   `json:"sites,omitempty"`
}
