/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FirewallInboundRuleAction struct {
	Type string `json:"type"`
	Nat FirewallInboundRuleActionNat `json:"nat"`
	// The name of the interface from which traffic should be forwarded
	Interface string `json:"interface"`
	SubinterfaceId int32 `json:"subinterfaceId,omitempty"`
}
