/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayStatusMetricsSummary struct {
	Total int32 `json:"total,omitempty"`
	TunnelCount BasicMetricSummary `json:"tunnelCount,omitempty"`
	MemoryPct BasicMetricSummary `json:"memoryPct,omitempty"`
	FlowCount BasicMetricSummary `json:"flowCount,omitempty"`
	CpuPct BasicMetricSummary `json:"cpuPct,omitempty"`
	HandoffQueueDrops BasicMetricSummary `json:"handoffQueueDrops,omitempty"`
	ConnectedEdges BasicMetricSummary `json:"connectedEdges,omitempty"`
}
