/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject2 struct {
	Enterprises []int32 `json:"enterprises,omitempty"`
	EnterpriseProxyId int32 `json:"enterpriseProxyId,omitempty"`
	NetworkId int32 `json:"networkId,omitempty"`
	Links bool `json:"links,omitempty"`
}
