/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OperatorSsoAuthenticationConfigurationConfigurationRoleConfigVcoToIdpRoleMap struct {
	OperatorBusiness []string `json:"Operator Business,omitempty"`
	OperatorStandardAdmin []string `json:"Operator Standard Admin,omitempty"`
	OperatorSuperuser []string `json:"Operator Superuser,omitempty"`
	OperatorSupport []string `json:"Operator Support,omitempty"`
}
