/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Filter1Rules struct {
	Field string `json:"field,omitempty"`
	Op string `json:"op,omitempty"`
	Values []string `json:"values,omitempty"`
}
