/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SecurityVnfServicePaloAltoNetworksManagementServer struct {
	Primary string `json:"primary,omitempty"`
	Secondary string `json:"secondary,omitempty"`
	AuthKey string `json:"authKey,omitempty"`
}
