/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type ApplicationMetadata struct {
	BlobId int32 `json:"blobId"`
	Created time.Time `json:"created"`
	Description string `json:"description"`
	FileName string `json:"fileName"`
	Id int32 `json:"id"`
	LogicalId string `json:"logicalId"`
	Manifest ApplicationMetadataManifest `json:"manifest"`
	Modified time.Time `json:"modified"`
	Name string `json:"name"`
	NetworkId int32 `json:"networkId"`
	Type string `json:"type"`
	UploadDetails ApplicationMetadataUploadDetails `json:"uploadDetails"`
	Version string `json:"version"`
}
