/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WanDataLinks struct {
	LogicalId string `json:"logicalId,omitempty"`
	InternalId string `json:"internalId,omitempty"`
	Discovery string `json:"discovery,omitempty"`
	Mode string `json:"mode,omitempty"`
	Type string `json:"type,omitempty"`
	Name string `json:"name,omitempty"`
	Isp string `json:"isp,omitempty"`
	PublicIpAddress string `json:"publicIpAddress,omitempty"`
	SourceIpAddress string `json:"sourceIpAddress,omitempty"`
	NextHopIpAddress string `json:"nextHopIpAddress,omitempty"`
	CustomVlanId bool `json:"customVlanId,omitempty"`
	VlanId int32 `json:"vlanId,omitempty"`
	Enable8021P bool `json:"enable8021P,omitempty"`
	Priority8021P int32 `json:"priority8021P,omitempty"`
	VirtualIpAddress string `json:"virtualIpAddress,omitempty"`
	DynamicBwAdjustmentEnabled bool `json:"dynamicBwAdjustmentEnabled,omitempty"`
	BwMeasurement string `json:"bwMeasurement,omitempty"`
	UpstreamMbps string `json:"upstreamMbps,omitempty"`
	DownstreamMbps string `json:"downstreamMbps,omitempty"`
	BackupOnly bool `json:"backupOnly,omitempty"`
	OverheadBytes int32 `json:"overheadBytes,omitempty"`
	UdpHolePunching bool `json:"udpHolePunching,omitempty"`
	MTU int32 `json:"MTU,omitempty"`
	MplsNetwork string `json:"mplsNetwork,omitempty"`
	DscpTag string `json:"dscpTag,omitempty"`
	StaticSlaEnabled bool `json:"staticSlaEnabled,omitempty"`
	ClassesofServiceEnabled bool `json:"classesofServiceEnabled,omitempty"`
	EncryptOverlay bool `json:"encryptOverlay,omitempty"`
	StaticSLA WanDataStaticSla `json:"staticSLA,omitempty"`
	ClassesOfService WanDataClassesOfService `json:"classesOfService,omitempty"`
	Interfaces []string `json:"interfaces,omitempty"`
	LastActive string `json:"lastActive,omitempty"`
}
