/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NetworkUpdateNetworkGatewayPoolAttributes struct {
	NetworkId int32 `json:"networkId,omitempty"`
	EnterpriseProxyId int32 `json:"enterpriseProxyId,omitempty"`
	// alias for `gatewayPoolId`
	Id int32 `json:"id"`
	GatewayPoolId int32 `json:"gatewayPoolId,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	HandOffType string `json:"handOffType,omitempty"`
}
