/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type GatewayRole struct {
	Created time.Time `json:"created,omitempty"`
	GatewayId int32 `json:"gatewayId,omitempty"`
	GatewayRole string `json:"gatewayRole,omitempty"`
	Required int32 `json:"required,omitempty"`
}
