/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SystemPropertyGetSystemProperties struct {
	// Filter for properties matching a given group prefix
	Group string `json:"group,omitempty"`
	// If true, transforms query result from rowset to single object with attribute names matching property names fetched
	Normalize bool `json:"normalize,omitempty"`
}
