/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeDeviceSettingsDataBgp struct {
	ASN string `json:"ASN,omitempty"`
	ConnectedRoutes bool `json:"connectedRoutes,omitempty"`
	DisableASPathCarryOver bool `json:"disableASPathCarryOver,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Filters []EdgeDeviceSettingsDataBgpFilters `json:"filters,omitempty"`
	Holdtime string `json:"holdtime,omitempty"`
	Keepalive string `json:"keepalive,omitempty"`
	Neighbors []ConfigEdgeBgpNeighbor `json:"neighbors,omitempty"`
	Networks []EdgeDeviceSettingsDataBgpNetworks `json:"networks,omitempty"`
	OverlayPrefix bool `json:"overlayPrefix,omitempty"`
	PropagateUplink bool `json:"propagateUplink,omitempty"`
	RouterId string `json:"routerId,omitempty"`
	UplinkCommunity int32 `json:"uplinkCommunity,omitempty"`
}
