/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsVrrpVirtualRouter struct {
	CidrIp string `json:"cidrIp,omitempty"`
	Interface string `json:"interface,omitempty"`
	Interval int32 `json:"interval,omitempty"`
	Preempt bool `json:"preempt,omitempty"`
	PreemptDelay int32 `json:"preemptDelay,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	SubinterfaceId int32 `json:"subinterfaceId,omitempty"`
	VlanId int32 `json:"vlanId,omitempty"`
	Vrid int32 `json:"vrid,omitempty"`
}
