/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsDataModelsVirtualLanInterfaces struct {
	Space        string                   `json:"space,omitempty"`
	Name         string                   `json:"name,omitempty"`
	Type         string                   `json:"type,omitempty"`
	Cwp          bool                     `json:"cwp,omitempty"`
	PortMode     string                   `json:"portMode,omitempty"`
	UntaggedVlan string                   `json:"untaggedVlan,omitempty"`
	Disabled     bool                     `json:"disabled,omitempty"`
	L2           EdgeDeviceSettingsDataL2 `json:"l2,omitempty"`
	VlanIds      []int32                  `json:"vlanIds,omitempty"`
}
