/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsAllOf struct {
	Data DeviceSettingsData `json:"data,omitempty"`
	Refs DeviceSettingsRefs `json:"refs,omitempty"`
}
