/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeUpdateEdgeAdminPassword struct {
	Id int32 `json:"id"`
	Username string `json:"username,omitempty"`
	Password string `json:"password"`
}
