/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FirewallGetEnterpriseFirewallLogs struct {
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	Interval Interval `json:"interval,omitempty"`
	Filter EnterpriseGetEnterpriseAlertsFilter `json:"filter,omitempty"`
	Rules []string `json:"rules,omitempty"`
	SourceIps []string `json:"sourceIps,omitempty"`
	DestIps []string `json:"destIps,omitempty"`
	Edges []int32 `json:"edges,omitempty"`
	With []string `json:"with,omitempty"`
}
