/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WanDataStaticSla struct {
	LatencyMs int32 `json:"latencyMs,omitempty"`
	JitterMs int32 `json:"jitterMs,omitempty"`
	LossPct int32 `json:"lossPct,omitempty"`
}
