/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConfigurationUpdateConfigurationModule struct {
	Id int32 `json:"id,omitempty"`
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	Basic bool `json:"basic,omitempty"`
	Update ConfigurationModule `json:"_update,omitempty"`
}
