/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EventGetOperatorEvents struct {
	NetworkId int32 `json:"networkId,omitempty"`
	Interval Interval `json:"interval,omitempty"`
	Filter Filter1 `json:"filter,omitempty"`
	GatewayId []int32 `json:"gatewayId,omitempty"`
}
