/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ControlPlaneDataVpnEdgeToEdgeDetail struct {
	Dynamic ControlPlaneDataVpnEdgeToEdgeDetailDynamic `json:"dynamic,omitempty"`
	EncryptionProtocol string `json:"encryptionProtocol,omitempty"`
	ProfileIsolation ControlPlaneDataVpnEdgeToEdgeDetailProfileIsolation `json:"profileIsolation,omitempty"`
	UseCloudGateway bool `json:"useCloudGateway,omitempty"`
	VpnHubs []map[string]interface{} `json:"vpnHubs,omitempty"`
	AutoSelectVpnHubs bool `json:"autoSelectVpnHubs,omitempty"`
}
