/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterData struct {
	Authentication DataCenterDataAuthentication `json:"authentication,omitempty"`
	IsCDE bool `json:"isCDE,omitempty"`
	IsServiceEnabled bool `json:"isServiceEnabled,omitempty"`
	Primary DataCenterVpnTunnel `json:"primary,omitempty"`
	Secondary DataCenterVpnTunnel `json:"secondary,omitempty"`
	Subnets []DataCenterDataSubnets `json:"subnets,omitempty"`
	IaasProvider DataCenterDataIaasProvider `json:"iaasProvider,omitempty"`
}
