/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseSetEnterpriseAllAlertsRecipientsEnterpriseUsers struct {
	EnterpriseUserId int32 `json:"enterpriseUserId,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	SmsEnabled bool `json:"smsEnabled,omitempty"`
	EmailEnabled bool `json:"emailEnabled,omitempty"`
	MobileEnabled bool `json:"mobileEnabled,omitempty"`
}
