/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ImageUpdateData struct {
	BuildNumber string `json:"buildNumber"`
	ProfileDeviceFamily string `json:"profileDeviceFamily"`
	ProfileVersion string `json:"profileVersion"`
	ScheduledStartTime ImageUpdateScheduledTime `json:"scheduledStartTime,omitempty"`
	SoftwarePackageId int32 `json:"softwarePackageId"`
	SoftwarePackageName string `json:"softwarePackageName"`
	Version string `json:"version"`
	WindowDurationMins int32 `json:"windowDurationMins"`
	Windowed bool `json:"windowed"`
}
