/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VcoInventoryGetInventoryItems struct {
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	ModifiedSince int32 `json:"modifiedSince,omitempty"`
	With []string `json:"with,omitempty"`
}
