/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeEnableEdgeForEdgeHub struct {
	ConfigurationID int32 `json:"configurationId,omitempty"`
	EdgeID          int32 `json:"edgeId,omitempty"`
	EnterpriseID    int32 `json:"enterpriseId,omitempty"`
	ModuleID        int32 `json:"moduleId,omitempty"`
	SegmentObjectID int32 `json:"segmentObjectId,omitempty"`
}
