/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosSegments struct {
	Rules []QosBusinessRules `json:"rules"`
	Defaults []QosBusinessRules `json:"defaults,omitempty"`
	WebProxy QosSegmentsWebProxy `json:"webProxy"`
	CosMapping QosSegmentsCosMapping `json:"cosMapping,omitempty"`
	Segment ConfigurationModuleSegmentMetadata `json:"segment"`
}
