/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ControlPlaneDataVpn struct {
	DataCenterEdges []ControlPlaneDataVpnDataCenterEdges `json:"dataCenterEdges,omitempty"`
	EdgeToDataCenter bool `json:"edgeToDataCenter,omitempty"`
	EdgeToEdge bool `json:"edgeToEdge,omitempty"`
	EdgeToEdgeDetail ControlPlaneDataVpnEdgeToEdgeDetail `json:"edgeToEdgeDetail,omitempty"`
	EdgeToEdgeList []ControlPlaneDataVpnEdgeToEdgeList `json:"edgeToEdgeList,omitempty"`
}
