/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayUpdateGatewayAttributes struct {
	Id int32 `json:"id"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Site Site `json:"site,omitempty"`
	IpsecGatewayDetail GatewayHandoffDetail `json:"ipsecGatewayDetail,omitempty"`
	HandOffDetail GatewayHandoffDetail `json:"handOffDetail,omitempty"`
	Roles []map[string]interface{} `json:"roles,omitempty"`
}
