/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeDeviceSettingsDataDhcpServer struct {
	BaseDhcpAddr int32 `json:"baseDhcpAddr,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	LeaseTimeSeconds int32 `json:"leaseTimeSeconds,omitempty"`
	DhcpRelay EdgeDeviceSettingsDataLanDhcpDhcpRelay `json:"dhcpRelay,omitempty"`
	NumDhcpAddr int32 `json:"numDhcpAddr,omitempty"`
	StaticReserved int32 `json:"staticReserved,omitempty"`
	Options []EdgeDeviceSettingsDataDhcpServerOptions `json:"options,omitempty"`
}
