/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)

type FirewallLogData struct {
	Id int32 `json:"id,omitempty"`
	EdgeId int32 `json:"edgeId,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	Allow int32 `json:"allow,omitempty"`
	RuleLogicalId string `json:"ruleLogicalId,omitempty"`
	Interface string `json:"interface,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	SourceIp string `json:"sourceIp,omitempty"`
	SourcePort int32 `json:"sourcePort,omitempty"`
	DestIp string `json:"destIp,omitempty"`
	DestPort int32 `json:"destPort,omitempty"`
	IcmpType string `json:"icmpType,omitempty"`
	Length int32 `json:"length,omitempty"`
}
