/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FirewallInboundRuleActionNat struct {
	LanIp string `json:"lan_ip"`
	LanPort int32 `json:"lan_port,omitempty"`
	Outbound bool `json:"outbound,omitempty"`
}
