/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type EdgeLinkMetric string

// List of edge_link_metric
const (
	P1_BYTES_RX EdgeLinkMetric = "p1BytesRx"
	P1_BYTES_TX EdgeLinkMetric = "p1BytesTx"
	P1_PACKETS_RX EdgeLinkMetric = "p1PacketsRx"
	P1_PACKETS_TX EdgeLinkMetric = "p1PacketsTx"
	P2_BYTES_RX EdgeLinkMetric = "p2BytesRx"
	P2_BYTES_TX EdgeLinkMetric = "p2BytesTx"
	P2_PACKETS_RX EdgeLinkMetric = "p2PacketsRx"
	P2_PACKETS_TX EdgeLinkMetric = "p2PacketsTx"
	P3_BYTES_RX EdgeLinkMetric = "p3BytesRx"
	P3_BYTES_TX EdgeLinkMetric = "p3BytesTx"
	P3_PACKETS_RX EdgeLinkMetric = "p3PacketsRx"
	P3_PACKETS_TX EdgeLinkMetric = "p3PacketsTx"
	CONTROL_BYTES_RX EdgeLinkMetric = "controlBytesRx"
	CONTROL_BYTES_TX EdgeLinkMetric = "controlBytesTx"
	CONTROL_PACKETS_RX EdgeLinkMetric = "controlPacketsRx"
	CONTROL_PACKETS_TX EdgeLinkMetric = "controlPacketsTx"
	BEST_BW_KBPS_RX EdgeLinkMetric = "bestBwKbpsRx"
	BEST_BW_KBPS_TX EdgeLinkMetric = "bestBwKbpsTx"
	BEST_JITTER_MS_RX EdgeLinkMetric = "bestJitterMsRx"
	BEST_JITTER_MS_TX EdgeLinkMetric = "bestJitterMsTx"
	BEST_LATENCY_MS_RX EdgeLinkMetric = "bestLatencyMsRx"
	BEST_LATENCY_MS_TX EdgeLinkMetric = "bestLatencyMsTx"
	BEST_LOSS_PCT_RX EdgeLinkMetric = "bestLossPctRx"
	BEST_LOSS_PCT_TX EdgeLinkMetric = "bestLossPctTx"
	BPS_OF_BEST_PATH_RX EdgeLinkMetric = "bpsOfBestPathRx"
	BPS_OF_BEST_PATH_TX EdgeLinkMetric = "bpsOfBestPathTx"
	SIGNAL_STRENGTH EdgeLinkMetric = "signalStrength"
	SCORE_TX EdgeLinkMetric = "scoreTx"
	SCORE_RX EdgeLinkMetric = "scoreRx"
)