/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConfigEdgeBgpNeighbor struct {
	NeighborAS string `json:"neighborAS,omitempty"`
	NeighborIp string `json:"neighborIp,omitempty"`
	NeighborTag string `json:"neighborTag,omitempty"`
	InboundFilter ConfigEdgeBgpFilterSet `json:"inboundFilter,omitempty"`
	OutboundFilter ConfigEdgeBgpFilterSet `json:"outboundFilter,omitempty"`
	AllowAS bool `json:"allowAS,omitempty"`
	Connect string `json:"connect,omitempty"`
	DefaultRoute bool `json:"defaultRoute,omitempty"`
	Holdtime string `json:"holdtime,omitempty"`
	Keepalive string `json:"keepalive,omitempty"`
	EnableMd5 bool `json:"enableMd5,omitempty"`
	Md5Password string `json:"md5Password,omitempty"`
}
