/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EdgeDeviceSettingsData struct {
	Bgp EdgeDeviceSettingsDataBgp `json:"bgp,omitempty"`
	Lan EdgeDeviceSettingsDataLan `json:"lan,omitempty"`
	RoutedInterfaces []EdgeDeviceSettingsDataRoutedInterfaces `json:"routedInterfaces,omitempty"`
	Routes EdgeDeviceSettingsDataRoutes `json:"routes,omitempty"`
	Ha EdgeDeviceSettingsDataHa `json:"ha,omitempty"`
	Dns EdgeDeviceSettingsDataDns `json:"dns,omitempty"`
	Netflow EdgeDeviceSettingsDataNetflow `json:"netflow,omitempty"`
	Vqm EdgeDeviceSettingsDataVqm `json:"vqm,omitempty"`
	Vrrp EdgeDeviceSettingsDataVrrp `json:"vrrp,omitempty"`
	Snmp EdgeDeviceSettingsDataSnmp `json:"snmp,omitempty"`
	MultiSourceQos EdgeDeviceSettingsDataMultiSourceQos `json:"multiSourceQos,omitempty"`
	Tacacs EdgeDeviceSettingsDataTacacs `json:"tacacs,omitempty"`
}
