/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsLanInterface struct {
	Override           bool                          `json:"override,omitempty"`
	Name               string                        `json:"name,omitempty"`
	Cwp                bool                          `json:"cwp"`
	Disabled           bool                          `json:"disabled,omitempty"`
	L2                 *DeviceSettingsLanInterfaceL2 `json:"l2,omitempty"`
	PortMode           string                        `json:"portMode,omitempty"`
	Space              string                        `json:"space,omitempty"`
	Type               string                        `json:"type,omitempty"`
	UntaggedVlan       int32                         `json:"untaggedVlan,omitempty"`
	VlanIds            []int32                       `json:"vlanIds"`
	AuthenticationType string                        `json:"authenticationType,omitempty"`
	BroadcastSsid      bool                          `json:"broadcastSsid,omitempty"`
	Passphrase         string                        `json:"passphrase,omitempty"`
	Ssid               string                        `json:"ssid,omitempty"`
	SecurityMode       string                        `json:"securityMode,omitempty"`
}
