/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Ref struct {
	Id int32 `json:"id,omitempty"`
	ConfigurationId int32 `json:"configurationId"`
	ModuleId int32 `json:"moduleId"`
	LogicalId string `json:"logicalId"`
	EnterpriseObjectId int32 `json:"enterpriseObjectId"`
	SegmentLogicalId string `json:"segmentLogicalId"`
	SegmentObjectId int32 `json:"segmentObjectId"`
	Ref string `json:"ref,omitempty"`
}
