/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject3 struct {
	EnterpriseId int32 `json:"enterpriseId,omitempty"`
	EnterpriseProxyId int32 `json:"enterpriseProxyId,omitempty"`
	IsDelegated bool `json:"isDelegated"`
}
