/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsDns struct {
	Override         bool                              `json:"override,omitempty"`
	PrimaryProvider  DeviceSettingsDnsPrimaryProvider  `json:"primaryProvider,omitempty"`
	BackupProvider   DeviceSettingsDnsBackupProvider   `json:"backupProvider,omitempty"`
	PrivateProviders DeviceSettingsDnsPrivateProviders `json:"privateProviders,omitempty"`
}
