/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001 struct {
	EdgeId int32 `json:"edgeId,omitempty"`
	EdgeName string `json:"edgeName,omitempty"`
	TunnelCount int32 `json:"tunnelCount,omitempty"`
	MemoryPct float32 `json:"memoryPct,omitempty"`
	FlowCount float32 `json:"flowCount,omitempty"`
	CpuPct float32 `json:"cpuPct,omitempty"`
	HandoffQueueDrops int32 `json:"handoffQueueDrops,omitempty"`
}
