/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterVpnTunnelIpsecsa struct {
	AuthenticationAlgorithm string `json:"authenticationAlgorithm,omitempty"`
	EncryptionAlgorithm string `json:"encryptionAlgorithm,omitempty"`
	LifeTimeSeconds int32 `json:"lifeTimeSeconds,omitempty"`
	Mode string `json:"mode,omitempty"`
	PerfectForwardSecurity string `json:"perfectForwardSecurity,omitempty"`
	Protocol string `json:"protocol,omitempty"`
}
