/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SetClientDeviceHostName struct {
	EnterpriseId int32 `json:"enterpriseId"`
	ClientDeviceId int32 `json:"clientDeviceId,omitempty"`
	HostName string `json:"hostName"`
	MacAddress string `json:"macAddress,omitempty"`
	IpAddress string `json:"ipAddress,omitempty"`
}
