/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DataCenterVpnTunnelFragmentationAvoidance struct {
	TcpMssAdjustmentBytes int32 `json:"tcpMssAdjustmentBytes,omitempty"`
	ClearDontFragmentBit string `json:"clearDontFragmentBit,omitempty"`
	FragmentationStyle string `json:"fragmentationStyle,omitempty"`
}
