/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsData struct {
	Lan            DeviceSettingsDataLan                    `json:"lan,omitempty"`
	Ospf           DeviceSettingsDataOspf                   `json:"ospf,omitempty"`
	Bgp            DeviceSettingsDataBgp                    `json:"bgp,omitempty"`
	Dns            EdgeDeviceSettingsDataDns                `json:"dns,omitempty"`
	Authentication EdgeDeviceSettingsDataDnsPrimaryProvider `json:"authentication,omitempty"`
	SoftwareUpdate DeviceSettingsDataSoftwareUpdate         `json:"softwareUpdate,omitempty"`
	RadioSettings  DeviceSettingsDataRadioSettings          `json:"radioSettings,omitempty"`
	Netflow        DeviceSettingsDataNetflow                `json:"netflow,omitempty"`
	Vqm            DeviceSettingsDataVqm                    `json:"vqm,omitempty"`
	Snmp           DeviceSettingsDataSnmp                   `json:"snmp,omitempty"`
	MultiSourceQos DeviceSettingsDataMultiSourceQos         `json:"multiSourceQos,omitempty"`
	Models         DeviceSettingsDataModels                 `json:"models,omitempty"`
	Vpn            DeviceSettingsDataVpn                    `json:"vpn,omitempty"`
}
