/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SecurityVnfImageData struct {
	Service LogicalidReference `json:"service,omitempty"`
	IN_PROGRESS VnfImageDownloadEventDetail `json:"IN_PROGRESS,omitempty"`
	COMPLETED VnfImageDownloadEventDetail `json:"COMPLETED,omitempty"`
	FAILED VnfImageDownloadEventDetail `json:"FAILED,omitempty"`
}
