/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GatewayHandoffEdgeAllOf struct {
	EdgeId int32 `json:"edgeId,omitempty"`
	IsPrimary int32 `json:"isPrimary,omitempty"`
	Pinned int32 `json:"pinned,omitempty"`
	EnterpriseLogicalId string `json:"enterpriseLogicalId,omitempty"`
	EnterpriseName string `json:"enterpriseName,omitempty"`
}
