/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsDataVpn struct {
	Enabled          bool                                  `json:"enabled,omitempty"`
	EdgeToDataCenter bool                                  `json:"edgeToDataCenter,omitempty"`
	Ref              string                                `json:"ref,omitempty"`
	EdgeToEdgeHub    DeviceSettingsDataVpnEdgeToEdgeHub    `json:"edgeToEdgeHub,omitempty"`
	EdgeToEdge       bool                                  `json:"edgeToEdge,omitempty"`
	EdgeToEdgeDetail DeviceSettingsDataVpnEdgeToEdgeDetail `json:"edgeToEdgeDetail,omitempty"`
}
