/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EnterpriseProxySsoAuthenticationConfigurationConfigurationRoleConfig struct {
	DefaultRole string `json:"defaultRole,omitempty"`
	OidcRolesEnabled bool `json:"oidcRolesEnabled,omitempty"`
	RoleAttribute string `json:"roleAttribute,omitempty"`
	VcoToIdpRoleMap EnterpriseProxySsoAuthenticationConfigurationConfigurationRoleConfigVcoToIdpRoleMap `json:"vcoToIdpRoleMap,omitempty"`
}
