/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
type BasicMetric string

// List of basic_metric
const (
	PACKETS_RX BasicMetric = "packetsRx"
	PACKETS_TX BasicMetric = "packetsTx"
	TOTAL_PACKETS BasicMetric = "totalPackets"
	BYTES_RX BasicMetric = "bytesRx"
	BYTES_TX BasicMetric = "bytesTx"
	TOTAL_BYTES BasicMetric = "totalBytes"
)