/*
 * VeloCloud Orchestrator API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.3.2
 * Contact: support@velocloud.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeviceSettingsSegment struct {
	Authentication     DeviceSettingsAuthentication       `json:"authentication,omitempty"`
	Bgp                *DeviceSettingsBgp                 `json:"bgp,omitempty"`
	Css                *DeviceSettingsCloudSecurity       `json:"css,omitempty"`
	Dns                *DeviceSettingsDns                 `json:"dns,omitempty"`
	HandOffControllers *DeviceSettingsHandoffGateways     `json:"handOffControllers,omitempty"`
	HandOffGateways    *DeviceSettingsHandoffGateways     `json:"handOffGateways,omitempty"`
	MultiSourceQos     *DeviceSettingsMultiSourceQos      `json:"multiSourceQos,omitempty"`
	Multicast          *DeviceSettingsMulticast           `json:"multicast,omitempty"`
	Nat                *DeviceSettingsNat                 `json:"nat,omitempty"`
	Netflow            DeviceSettingsNetflow              `json:"netflow,omitempty"`
	Ntp                *DeviceSettingsNtp                 `json:"ntp,omitempty"`
	Ospf               *DeviceSettingsOspf                `json:"ospf,omitempty"`
	Routes             *DeviceSettingsSegmentRoutes       `json:"routes,omitempty"`
	Segment            ConfigurationModuleSegmentMetadata `json:"segment"`
	Snmp               *DeviceSettingsSnmp                `json:"snmp,omitempty"`
	Syslog             DeviceSettingsSyslog               `json:"syslog,omitempty"`
	Vpn                DeviceSettingsVpn                  `json:"vpn,omitempty"`
	Vqm                *DeviceSettingsVqm                 `json:"vqm,omitempty"`
	Vrrp               *DeviceSettingsVrrp                `json:"vrrp,omitempty"`
}
